name: "Build documentation"

on:
  push:
    branches:
      - source
  workflow_dispatch: {}

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Typst
        uses: typst-community/setup-typst@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python requirements
        run: |
          pip install -U -r requirements.txt

      - name: Run documentation build script
        run: |
          python build.py

      - name: Transfer manifests to deploy branch
        shell: bash
        run: |
          # Copy the manifests to a temporary directory
          export DOCUMENTATION_OUTPUT_TEMP=$(mktemp -d)
          cp -r output/* $DOCUMENTATION_OUTPUT_TEMP

          # Clear the repo so we can switch branches
          git clean -dfx

          # Switch branches to deploy
          git fetch origin deploy
          git checkout deploy

          # If the last commit was by GitHub Actions, revert it
          if [[ "$(git show -s --format='%ae' HEAD)" == *"github-actions"* ]]; then
            git reset --hard HEAD^;
          fi

          # Copy artifacts here
          cp -r ${DOCUMENTATION_OUTPUT_TEMP}/* .

          # Upload the documentation
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Autogenerated documentation created at $(date +%Y-%m-%d_%H-%M)"
          git push --force
